SET CLUSTER '';
SET DEFAULT_TABLE_TYPE 0;
SET WRITE_DELAY 500;
SET DEFAULT_LOCK_TIMEOUT 2000;
SET CACHE_SIZE 16384;
;
CREATE USER IF NOT EXISTS "" SALT '1aea40d96e4912a7' HASH 'bd326299831655fa0d1a3c30da7a29f7329734266d80ea3838f25e0a1d0c6232' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_22D178A5_1214_462D_ADEA_6E39664CB44A START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1C63F614_55C7_4AF3_98D5_0FD1A8B20128 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_174A49F3_231B_42B7_BD2A_A1B3A6F70E23 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4C56BE5C_E94F_4E58_80E3_00F494BFAFC7 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1B9449D1_A66A_4BC6_853E_DADFBC769B3C START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9CA84A22_84BF_4F1C_93CF_9F9FB41037DE START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_489E1450_24EE_4430_820A_88705D20F5F8 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_63AE8D4A_878D_4EB0_8235_66B278D29CD3 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AE9C4489_9148_4E3F_A02A_343402A0B13C START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.DZIEN(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_22D178A5_1214_462D_ADEA_6E39664CB44A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_22D178A5_1214_462D_ADEA_6E39664CB44A,
    DATA DATE,
    ILOSC_INNYCH INTEGER,
    ILOSC_KADRY INTEGER,
    ILOSC_UCZESTNIKOW INTEGER,
    STAWKADZIENNA NUMERIC
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DZIEN;
CREATE CACHED TABLE PUBLIC.DANIE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9CA84A22_84BF_4F1C_93CF_9F9FB41037DE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9CA84A22_84BF_4F1C_93CF_9F9FB41037DE,
    COSTSTRICT BIT NOT NULL,
    KOSZT NUMERIC,
    NAZWA VARCHAR(255) NOT NULL,
    POSILEK_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DANIE;
CREATE CACHED TABLE PUBLIC.PARTIA(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4C56BE5C_E94F_4E58_80E3_00F494BFAFC7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4C56BE5C_E94F_4E58_80E3_00F494BFAFC7,
    CENA NUMERIC NOT NULL,
    DATA_KSIEGOWANIA DATE NOT NULL,
    DATA_WAZNOSCI DATE,
    DATA_WPROWADZENIA DATE,
    ILOSC_POCZ NUMERIC NOT NULL,
    ILOSC_TERAZ NUMERIC NOT NULL,
    JEDNOSTKA VARCHAR(255) NOT NULL,
    NUMER_FAKTURY VARCHAR(100) NOT NULL,
    NUMER_LINII INTEGER,
    OPIS VARCHAR(1000),
    SPECYFIKATOR VARCHAR(255) NOT NULL,
    PRODUKT_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTIA;
CREATE CACHED TABLE PUBLIC.PRODUKT(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1C63F614_55C7_4AF3_98D5_0FD1A8B20128) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1C63F614_55C7_4AF3_98D5_0FD1A8B20128,
    DATA_WAZNOSCI INTEGER NOT NULL CHECK (DATA_WAZNOSCI >= -1),
    JEDNOSTKA VARCHAR(50),
    NAZWA VARCHAR(50) NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUKT;
CREATE CACHED TABLE PUBLIC.POSILEK_DANIE(
    POSILEK_ID BIGINT NOT NULL,
    DANIA_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POSILEK_DANIE;
CREATE CACHED TABLE PUBLIC.WYPROWADZENIE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1B9449D1_A66A_4BC6_853E_DADFBC769B3C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1B9449D1_A66A_4BC6_853E_DADFBC769B3C,
    DATA_UTWORZENIA TIMESTAMP NOT NULL, -- 1
    DATA_WYPROWADZENIA TIMESTAMP NOT NULL, -- 2
    ILOSC_JEDNOSTEK NUMERIC NOT NULL, -- 3
    TYTULEM VARCHAR(255) NOT NULL, -- 4
    DANIE_ID BIGINT, -- 5
    PARTIA_ID BIGINT NOT NULL -- 6 
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WYPROWADZENIE;
CREATE CACHED TABLE PUBLIC.CONFIG_ENTRY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_63AE8D4A_878D_4EB0_8235_66B278D29CD3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_63AE8D4A_878D_4EB0_8235_66B278D29CD3,
    DESCRIPTION VARCHAR(2000),
    EDITABLE BIT,
    ENTRY_NAME VARCHAR(100) NOT NULL,
    ENTRY_VALUE VARCHAR(10000),
    VISIBLE BIT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONFIG_ENTRY;

CREATE CACHED TABLE PUBLIC.PLANOWANE_WYPROWADZENIE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_174A49F3_231B_42B7_BD2A_A1B3A6F70E23) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_174A49F3_231B_42B7_BD2A_A1B3A6F70E23,
    ILOSC_JEDNOSTEK NUMERIC NOT NULL,
    JEDNOSTKA VARCHAR(255) NOT NULL,
    SPECYFIKATOR VARCHAR(255),
    DANIE_ID BIGINT,
    PRODUKT_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLANOWANE_WYPROWADZENIE;
CREATE CACHED TABLE PUBLIC.PLANOWANE_WYPROWADZENIE_WYPROWADZENIE(
    PLANOWANE_WYPROWADZENIE_ID BIGINT NOT NULL,
    WYPROWADZENIA_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLANOWANE_WYPROWADZENIE_WYPROWADZENIE;
CREATE CACHED TABLE PUBLIC.PRODUCT_SEARCH_CACHE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_489E1450_24EE_4430_820A_88705D20F5F8) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_489E1450_24EE_4430_820A_88705D20F5F8,
    JEDNOSTKA VARCHAR(255),
    NAZWAPRODUKTU VARCHAR(255) NOT NULL,
    PRODUCTID BIGINT NOT NULL,
    SPECYFIKATOR VARCHAR(255),
    JEDNOSTKA6 VARCHAR(255),
    NAZWA_PRODUKTU VARCHAR(255),
    PRODUCT_ID BIGINT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_SEARCH_CACHE;
CREATE CACHED TABLE PUBLIC.POSILEK(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AE9C4489_9148_4E3F_A02A_343402A0B13C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AE9C4489_9148_4E3F_A02A_343402A0B13C,
    COSTSTRICT BIT,
    DODATKOWY BIT,
    ILOSC_INNYCH INTEGER,
    ILOSC_KADRY INTEGER,
    ILOSC_UCZESTNIKOW INTEGER,
    KOSZT NUMERIC,
    NAZWA VARCHAR(255),
    DZIEN_ID BIGINT NOT NULL,
    COST_STRICT BIT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POSILEK;
ALTER TABLE PUBLIC.DANIE ADD CONSTRAINT PUBLIC.CONSTRAINT_3D PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PRODUKT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PARTIA ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.WYPROWADZENIE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.DZIEN ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PLANOWANE_WYPROWADZENIE ADD CONSTRAINT PUBLIC.CONSTRAINT_E2 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.CONFIG_ENTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);
ALTER TABLE PUBLIC.POSILEK ADD CONSTRAINT PUBLIC.CONSTRAINT_13 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PRODUCT_SEARCH_CACHE ADD CONSTRAINT PUBLIC.CONSTRAINT_3DF PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PRODUKT ADD CONSTRAINT PUBLIC.CONSTRAINT_18 UNIQUE(NAZWA);
ALTER TABLE PUBLIC.DZIEN ADD CONSTRAINT PUBLIC.CONSTRAINT_3E UNIQUE(DATA);
ALTER TABLE PUBLIC.POSILEK_DANIE ADD CONSTRAINT PUBLIC.CONSTRAINT_14 UNIQUE(DANIA_ID);
ALTER TABLE PUBLIC.POSILEK_DANIE ADD CONSTRAINT PUBLIC.FK3ECD1ECB5AD0908E FOREIGN KEY(POSILEK_ID) REFERENCES PUBLIC.POSILEK(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANOWANE_WYPROWADZENIE ADD CONSTRAINT PUBLIC.FKE20514D871C9638E FOREIGN KEY(DANIE_ID) REFERENCES PUBLIC.DANIE(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANOWANE_WYPROWADZENIE_WYPROWADZENIE ADD CONSTRAINT PUBLIC.FKB4813EA9180666F7 FOREIGN KEY(PLANOWANE_WYPROWADZENIE_ID) REFERENCES PUBLIC.PLANOWANE_WYPROWADZENIE(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANOWANE_WYPROWADZENIE ADD CONSTRAINT PUBLIC.FKE20514D884324C4E FOREIGN KEY(PRODUKT_ID) REFERENCES PUBLIC.PRODUKT(ID) NOCHECK;
ALTER TABLE PUBLIC.POSILEK_DANIE ADD CONSTRAINT PUBLIC.FK3ECD1ECB71C79212 FOREIGN KEY(DANIA_ID) REFERENCES PUBLIC.DANIE(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANOWANE_WYPROWADZENIE_WYPROWADZENIE ADD CONSTRAINT PUBLIC.FKB4813EA95E2C4B32 FOREIGN KEY(WYPROWADZENIA_ID) REFERENCES PUBLIC.WYPROWADZENIE(ID) NOCHECK;
ALTER TABLE PUBLIC.WYPROWADZENIE ADD CONSTRAINT PUBLIC.FK787FB1D0B5ABC366 FOREIGN KEY(PARTIA_ID) REFERENCES PUBLIC.PARTIA(ID) NOCHECK;
ALTER TABLE PUBLIC.DANIE ADD CONSTRAINT PUBLIC.FK3EC004D5AD0908E FOREIGN KEY(POSILEK_ID) REFERENCES PUBLIC.POSILEK(ID) NOCHECK;
ALTER TABLE PUBLIC.WYPROWADZENIE ADD CONSTRAINT PUBLIC.FK787FB1D071C9638E FOREIGN KEY(DANIE_ID) REFERENCES PUBLIC.DANIE(ID) NOCHECK;
ALTER TABLE PUBLIC.PARTIA ADD CONSTRAINT PUBLIC.FK8C3E344B84324C4E FOREIGN KEY(PRODUKT_ID) REFERENCES PUBLIC.PRODUKT(ID) NOCHECK;
ALTER TABLE PUBLIC.POSILEK ADD CONSTRAINT PUBLIC.FK4BE25D3D9393F52E FOREIGN KEY(DZIEN_ID) REFERENCES PUBLIC.DZIEN(ID) NOCHECK;


------------------------------------------------------------------------------------------------------------------------
--                                                                                                                    --
--                         RECZNE ZMIANY                                                                              --
--                                                                                                                    --
------------------------------------------------------------------------------------------------------------------------


ALTER TABLE CONFIG_ENTRY ADD CONSTRAINT CONFIG_ENTRY_NAME_UNIQUE UNIQUE(ENTRY_NAME);

CREATE TRIGGER CONFIG_ENTRY_UPDATE_TRIGGER BEFORE UPDATE ON CONFIG_ENTRY FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ConfigEntryTrigger";
CREATE TRIGGER CONFIG_ENTRY_DELETE_TRIGGER BEFORE DELETE ON CONFIG_ENTRY FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ConfigEntryTrigger";
CREATE TRIGGER WYPROWADZENIE_PRODUKT_INSERT_TRIGGER AFTER INSERT ON WYPROWADZENIE FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.WyprowadzenieUpdateProductTrigger";
CREATE TRIGGER WYPROWADZENIE_PRODUKT_DELETE_TRIGGER AFTER DELETE ON WYPROWADZENIE FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.WyprowadzenieUpdateProductTrigger";
CREATE TRIGGER WYPROWADZENIE_PRODUKT_UPDATE_TRIGGER AFTER UPDATE ON WYPROWADZENIE FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.WyprowadzenieUpdateProductTrigger";

INSERT INTO CONFIG_ENTRY(DESCRIPTION, EDITABLE, ENTRY_NAME, ENTRY_VALUE, VISIBLE) VALUES('Wersja bazy danych', TRUE, 'DATABASE_VERSION', '30000', FALSE);