SET CLUSTER '';
SET DEFAULT_TABLE_TYPE 0;
SET WRITE_DELAY 500;
SET DEFAULT_LOCK_TIMEOUT 2000;
SET CACHE_SIZE 16384;
;
CREATE USER IF NOT EXISTS "" SALT 'fafbb5d9ea275045' HASH '32cbee0dccf5825f1795f4a2aa1a92937b2e9cd535d36a0248c06c9a4438001c' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0A9DC212_82C7_425E_BDDF_33221B93772E START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_884F1827_0ABF_4110_A260_5C147C5BB112 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2154F932_7060_44AD_98A3_03E55200AD18 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4D6887C7_C3FB_41EE_9C80_2A6E5D6FBB51 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DCC5E7D9_8E3E_4965_9036_8F4A51DBE6C0 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E5B5C2C2_13CA_4A91_8D42_F4053E48AF48 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6A551429_31AC_4413_876D_AD2C724EE97A START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7D76EBF7_9345_4AEC_8C53_8CC99C65ECDA START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1EBF1F6B_2751_4B58_A781_65749C272270 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_14B83966_441A_4B49_BEF8_09BDFB667122 START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.BATCH(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E5B5C2C2_13CA_4A91_8D42_F4053E48AF48) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E5B5C2C2_13CA_4A91_8D42_F4053E48AF48,
    BOOKING_DATE DATE NOT NULL,
    CREATE_DATE DATE,
    CURRENT_QTY DECIMAL(12, 2) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    EXPIRY_DATE DATE,
    FAKTURA_NO VARCHAR(100) NOT NULL,
    LINE_NO INTEGER,
    PRICE DECIMAL(16, 6) NOT NULL,
    SPECIFIER VARCHAR(255) NOT NULL,
    START_QTY DECIMAL(12, 2) NOT NULL,
    UNIT VARCHAR(255) NOT NULL,
    PRODUCT_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BATCH;
CREATE CACHED TABLE PUBLIC.CONFIG_ENTRY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2154F932_7060_44AD_98A3_03E55200AD18) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2154F932_7060_44AD_98A3_03E55200AD18,
    DESCRIPTION VARCHAR(2000),
    EDITABLE BOOLEAN,
    ENTRY_NAME VARCHAR(100) NOT NULL,
    ENTRY_VALUE VARCHAR(10000),
    VISIBLE BOOLEAN
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONFIG_ENTRY;
CREATE CACHED TABLE PUBLIC.COURSE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DCC5E7D9_8E3E_4965_9036_8F4A51DBE6C0) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DCC5E7D9_8E3E_4965_9036_8F4A51DBE6C0,
    COST DECIMAL(19, 2),
    COST_STRICT BOOLEAN,
    NAME VARCHAR(255) NOT NULL,
    MEAL_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COURSE;
CREATE CACHED TABLE PUBLIC.DAY(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4D6887C7_C3FB_41EE_9C80_2A6E5D6FBB51) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4D6887C7_C3FB_41EE_9C80_2A6E5D6FBB51,
    DAY DATE,
    INNI_NO INTEGER,
    KADRA_NO INTEGER,
    UCZESTNICY_NO INTEGER,
    RATE DECIMAL(19, 2)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DAY;
CREATE CACHED TABLE PUBLIC.EXPENDITURE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_7D76EBF7_9345_4AEC_8C53_8CC99C65ECDA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7D76EBF7_9345_4AEC_8C53_8CC99C65ECDA,
    CREATE_DATE TIMESTAMP NOT NULL,
    EXPENDITURE_DATE TIMESTAMP NOT NULL,
    QUANTITY DECIMAL(19, 2) NOT NULL,
    TYTULEM VARCHAR(255) NOT NULL,
    BATCH_ID BIGINT NOT NULL,
    COURSE_ID BIGINT
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXPENDITURE;
CREATE CACHED TABLE PUBLIC.MEAL(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6A551429_31AC_4413_876D_AD2C724EE97A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6A551429_31AC_4413_876D_AD2C724EE97A,
    ADDITIONAL BOOLEAN,
    COST DECIMAL(19, 2),
    COST_STRICT BOOLEAN,
    NAME VARCHAR(255),
    INNI_NO INTEGER,
    KADRA_NO INTEGER,
    UCZESTNICY_NO INTEGER,
    DZIEN_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEAL;
CREATE CACHED TABLE PUBLIC.MEAL_COURSE(
    MEAL_ID BIGINT NOT NULL,
    DANIA_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEAL_COURSE;
CREATE CACHED TABLE PUBLIC.PLANNED_EXPENDITURE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0A9DC212_82C7_425E_BDDF_33221B93772E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0A9DC212_82C7_425E_BDDF_33221B93772E,
    QUANTITY DECIMAL(19, 2) NOT NULL,
    SPECIFIER VARCHAR(255),
    SPENT BOOLEAN,
    UNIT VARCHAR(255) NOT NULL,
    COURSE_ID BIGINT,
    PRODUCT_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLANNED_EXPENDITURE;
CREATE CACHED TABLE PUBLIC.PLANNED_EXPENDITURE_EXPENDITURE(
    PLANNED_EXPENDITURE_ID BIGINT NOT NULL,
    EXPENDITURES_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLANNED_EXPENDITURE_EXPENDITURE;
CREATE CACHED TABLE PUBLIC.PRODUCT(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1EBF1F6B_2751_4B58_A781_65749C272270) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1EBF1F6B_2751_4B58_A781_65749C272270,
    EXPIRY_DATE INTEGER NOT NULL CHECK (EXPIRY_DATE >= -1),
    NAME VARCHAR(50) NOT NULL,
    UNIT VARCHAR(50)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
CREATE CACHED TABLE PUBLIC.PRODUCT_SEARCH_CACHE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_14B83966_441A_4B49_BEF8_09BDFB667122) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_14B83966_441A_4B49_BEF8_09BDFB667122,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    SPECIFIER VARCHAR(255),
    UNIT VARCHAR(255)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_SEARCH_CACHE;
CREATE CACHED TABLE PUBLIC.UNIT_CONVERTER(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_884F1827_0ABF_4110_A260_5C147C5BB112) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_884F1827_0ABF_4110_A260_5C147C5BB112,
    CONVERTER_TYPE VARCHAR(255),
    REFLEXIVE BOOLEAN,
    REFLEXIVITY_DEPTH INTEGER,
    SCALE DECIMAL(12, 6),
    TRANSITIVE BOOLEAN,
    UNIT_FROM VARCHAR(255),
    UNIT_TO VARCHAR(255)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.UNIT_CONVERTER;
ALTER TABLE PUBLIC.PRODUCT ADD CONSTRAINT PUBLIC.CONSTRAINT_18 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.CONFIG_ENTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);
ALTER TABLE PUBLIC.DAY ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.UNIT_CONVERTER ADD CONSTRAINT PUBLIC.CONSTRAINT_EF PRIMARY KEY(ID);
ALTER TABLE PUBLIC.COURSE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.EXPENDITURE ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.BATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PLANNED_EXPENDITURE ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.PRODUCT_SEARCH_CACHE ADD CONSTRAINT PUBLIC.CONSTRAINT_3D PRIMARY KEY(ID);
ALTER TABLE PUBLIC.MEAL ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.DAY ADD CONSTRAINT PUBLIC.CONSTRAINT_10 UNIQUE(DATA);
ALTER TABLE PUBLIC.PRODUCT ADD CONSTRAINT PUBLIC.CONSTRAINT_185 UNIQUE(NAME);
ALTER TABLE PUBLIC.MEAL_COURSE ADD CONSTRAINT PUBLIC.CONSTRAINT_35 UNIQUE(DANIA_ID);
ALTER TABLE PUBLIC.BATCH ADD CONSTRAINT PUBLIC.FK3C0DF1A83C18F4E FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANNED_EXPENDITURE_EXPENDITURE ADD CONSTRAINT PUBLIC.FKAD748E48356D1D9 FOREIGN KEY(EXPENDITURES_ID) REFERENCES PUBLIC.EXPENDITURE(ID) NOCHECK;
ALTER TABLE PUBLIC.MEAL_COURSE ADD CONSTRAINT PUBLIC.FK36E68C376A066366 FOREIGN KEY(MEAL_ID) REFERENCES PUBLIC.MEAL(ID) NOCHECK;
ALTER TABLE PUBLIC.COURSE ADD CONSTRAINT PUBLIC.FK78A7CC3B6A066366 FOREIGN KEY(MEAL_ID) REFERENCES PUBLIC.MEAL(ID) NOCHECK;
ALTER TABLE PUBLIC.EXPENDITURE ADD CONSTRAINT PUBLIC.FK6529D5F62F1F166 FOREIGN KEY(COURSE_ID) REFERENCES PUBLIC.COURSE(ID) NOCHECK;
ALTER TABLE PUBLIC.EXPENDITURE ADD CONSTRAINT PUBLIC.FK6529D5FABD4D46E FOREIGN KEY(BATCH_ID) REFERENCES PUBLIC.BATCH(ID) NOCHECK;
ALTER TABLE PUBLIC.MEAL_COURSE ADD CONSTRAINT PUBLIC.FK36E68C376C6F5658 FOREIGN KEY(DANIA_ID) REFERENCES PUBLIC.COURSE(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANNED_EXPENDITURE_EXPENDITURE ADD CONSTRAINT PUBLIC.FKAD748E485DEE45D FOREIGN KEY(PLANNED_EXPENDITURE_ID) REFERENCES PUBLIC.PLANNED_EXPENDITURE(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANNED_EXPENDITURE ADD CONSTRAINT PUBLIC.FK53CF134462F1F166 FOREIGN KEY(COURSE_ID) REFERENCES PUBLIC.COURSE(ID) NOCHECK;
ALTER TABLE PUBLIC.MEAL ADD CONSTRAINT PUBLIC.FK240BC3F7D7EB4E FOREIGN KEY(DZIEN_ID) REFERENCES PUBLIC.DAY(ID) NOCHECK;
ALTER TABLE PUBLIC.PLANNED_EXPENDITURE ADD CONSTRAINT PUBLIC.FK53CF134483C18F4E FOREIGN KEY(PRODUCT_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;

------------------------------------------------------------------------------------------------------------------------
--                                                                                                                    --
--                         RECZNE ZMIANY                                                                              --
--                                                                                                                    --
------------------------------------------------------------------------------------------------------------------------


ALTER TABLE CONFIG_ENTRY ADD CONSTRAINT CONFIG_ENTRY_NAME_UNIQUE UNIQUE(ENTRY_NAME);

CREATE TRIGGER CONFIG_ENTRY_UPDATE_TRIGGER BEFORE UPDATE ON CONFIG_ENTRY FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ConfigEntryTrigger";
CREATE TRIGGER CONFIG_ENTRY_DELETE_TRIGGER BEFORE DELETE ON CONFIG_ENTRY FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ConfigEntryTrigger";
CREATE TRIGGER EXPENDITURE_PRODUCT_INSERT_TRIGGER AFTER INSERT ON EXPENDITURE FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ExpenditureUpdateProductTrigger";
CREATE TRIGGER EXPENDITURE_PRODUCT_DELETE_TRIGGER AFTER DELETE ON EXPENDITURE FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ExpenditureUpdateProductTrigger";
CREATE TRIGGER EXPENDITURE_PRODUCT_UPDATE_TRIGGER AFTER UPDATE ON EXPENDITURE FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ExpenditureUpdateProductTrigger";

INSERT INTO CONFIG_ENTRY(DESCRIPTION, EDITABLE, ENTRY_NAME, ENTRY_VALUE, VISIBLE) VALUES('Wersja bazy danych', TRUE, 'DATABASE_VERSION', '30000', FALSE);