UPDATE CONFIG_ENTRY SET ENTRY_VALUE = '30011' WHERE ENTRY_NAME = 'DATABASE_VERSION';

CREATE TRIGGER PSC_PRODUCT_ADD AFTER INSERT ON PRODUCT FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ProductUpdatePSCTrigger";
CREATE TRIGGER PSC_PRODUCT_UPDATE AFTER UPDATE ON PRODUCT FOR EACH ROW CALL "cx.ath.jbzdak.zarlock.db.trigger.ProductUpdatePSCTrigger";
